### ISSUE TITLE
Upload presentation to convenient service

### ISSUE THREAD

**Issue by KvanTTT** [PositiveTechnologies/seq2seq-web-attack-detection#1]
Maybe it makes sense to upload pdf presentation to https://speakerdeck.com/ or another presentations service? Take a look on the samples.

**Comment by amurzina** [comment]
done

**Comment by KvanTTT** [comment]
Where is the link?)

**Comment by amurzina** [comment]
The service proposed by you compresses the pdf more than github. Let's keep the current version, it's no big deal.
